const fs=require('node:fs'),ts=require('typescript'),{test}=require('node:test'),assert=require('node:assert/strict')
require.extensions['.ts']=(module,path)=>module._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,path)
const {guidedReply,nextInquiryField}=require('../lib/bot-conversation.ts')
test('context changes follow ups and grows a grounded brief',()=>{const history=[{role:'user',content:'I want to automate invoice processing'}];const first=guidedReply(history);history.push({role:'assistant',content:first.reply},{role:'user',content:'Invoices arrive by email and should become draft records'});const second=guidedReply(history,first.goal);assert.notEqual(first.reply,second.reply);assert.match(second.goal,/Invoices arrive/);assert.match(second.reply,/reviewed/);assert.equal(second.topic,'AI & Automation')})
test('no fabricated products or project evidence',()=>{assert.match(guidedReply([{role:'user',content:'Explore products'}]).reply,/No public/);assert.match(guidedReply([{role:'user',content:'Show case studies'}]).reply,/no approved/i)})
test('technology matches whole names and avoids Go in goal',()=>{assert.notEqual(guidedReply([{role:'user',content:'My goal is a useful application'}]).panel,'technologies');assert.equal(guidedReply([{role:'user',content:'Do you use Google Cloud?'}]).group,'Cloud platforms')})
test('inquiry requires valid details before review',()=>{const data={category:'AI & Automation',message:'Build an application',name:'Ada',email:'invalid',company:'',website:''};assert.equal(nextInquiryField(data),'email');data.email='ada@example.com';assert.equal(nextInquiryField(data),'review');data.name='';assert.equal(nextInquiryField(data),'name')})

test('explicit browsing switches topic while retaining the draft',()=>{assert.equal(guidedReply([{role:'user',content:'Explore products'}],'Build an AI app').panel,'products');assert.equal(guidedReply([{role:'assistant',content:'What should the AI application help someone do?'},{role:'user',content:'Improve cloud deployment'}],'Build an AI app').topic,'Cloud / DevOps')})
