'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUp, RotateCcw, Sparkles, Check } from 'lucide-react';
import { useGuide } from './guide-context';
import { TinkrBot } from './tinkrbot';
import { ContactForm } from './contact-form';
import { technologyGroups } from '@/lib/technologies';
import { products } from '@/lib/products';
import { botServices } from '@/lib/bot-knowledge';
import type { ChatMessage } from '@/lib/bot-conversation';
const chip = 'rounded-xl border border-primary/25 bg-primary/5 px-3 py-2 text-left text-sm hover:bg-primary/15 focus-visible:outline-2 focus-visible:outline-primary disabled:opacity-50';
function Cards({ message }: {
    message: ChatMessage;
}) {
    const guide = useGuide();
    if (message.panel === 'products')
        return <div className="mt-3 rounded-xl border border-border p-4">{products.length ? products.map(p => <a key={p.slug} href={p.url} className="block py-2 font-semibold text-primary">{p.name}<p className="text-sm text-muted-foreground">{p.description}</p></a>) : <><span className="text-xs uppercase tracking-widest text-primary">Product lab</span><p className="mt-2 text-sm">No public products listed yet.</p></>}</div>;
    if (message.panel === 'services')
        return <div className="mt-3 grid gap-2 sm:grid-cols-2">{botServices.map(service => <button disabled={guide.pending} key={service.title} className={chip} onClick={() => guide.prepare(service.category)}>{service.title}<span className="mt-1 block text-xs text-muted-foreground">{service.description}</span></button>)}</div>;
    if (message.panel === 'technologies')
        return <div className="mt-3 grid gap-2">{technologyGroups.filter(g => !message.group || g.title === message.group).map(g => <details key={g.title} open={message.group === g.title} className="rounded-xl border border-border p-3"><summary className="cursor-pointer text-sm font-semibold">{g.title}</summary><p className="mt-2 text-sm text-muted-foreground">{g.items.join(' · ')}</p><button className={`${chip} mt-3`} disabled={guide.pending} onClick={() => void guide.ask(`How could ${g.title} fit my project?`)}>Discuss fit</button></details>)}</div>;
    return null;
}
function Review() { const guide = useGuide(); return <div className="mt-4 rounded-2xl border border-primary/30 bg-primary/5 p-4">{guide.sent ? <div role="status"><Check className="mb-2 size-6 text-primary"/><p className="font-semibold">Inquiry sent. We will be in touch.</p></div> : <><h3 className="font-semibold">Review your inquiry</h3><dl className="mt-3 grid gap-2 text-sm"><div><dt className="text-muted-foreground">Goal</dt><dd className="whitespace-pre-wrap break-words">{guide.data.message}</dd></div><div><dt className="text-muted-foreground">Topic</dt><dd>{guide.data.category}</dd></div><div><dt className="text-muted-foreground">Reply to</dt><dd className="break-words">{guide.data.name} · {guide.data.email}</dd></div></dl><details className="my-3"><summary className="cursor-pointer text-sm text-primary">Edit details</summary><div className="mt-4"><ContactForm /></div></details><p className="mb-3 text-xs text-muted-foreground">Used to respond to your inquiry. <a href="/privacy" className="underline">Privacy</a></p>{guide.error && <p role="alert" className="mb-3 text-sm text-red-500">{guide.error}</p>}<button className="rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50" disabled={guide.pending} onClick={() => void guide.send()}>{guide.pending ? 'Sending…' : 'Send inquiry'}</button></>}</div>; }
export function BotWorkspace() {
    const guide = useGuide(), [input, setInput] = useState(''), end = useRef<HTMLDivElement>(null);
    useEffect(() => { if (guide.messages.length > 1)
        end.current?.scrollIntoView({ block: 'nearest', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }, [guide.messages, guide.pending]);
    function submit(e: FormEvent) { e.preventDefault(); if (guide.pending)
        return; void guide.ask(input); setInput(''); }
    return <section id="tinkrbot" className="relative px-4 pt-28 pb-12 sm:px-6"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center gap-4"><TinkrBot className="size-20 sm:size-24"/><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Sparkles className="size-4"/>AI. Products. Possibilities.</p><h1 className="text-3xl font-bold tracking-tight sm:text-5xl">Think it. Tinkr it.</h1><p className="mt-2 text-sm text-muted-foreground">One conversation with TinkrBot. From idea to next step.</p></div></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 overflow-hidden rounded-3xl border border-primary/20 bg-background/80 shadow-xl"><div className="flex items-center justify-between border-b border-border px-5 py-3"><div className="flex items-center gap-2 text-sm font-semibold"><span className="size-2 rounded-full bg-primary"/>TinkrBot<span className="text-xs font-normal text-muted-foreground" data-testid="bot-mode">{guide.mode}</span></div><button aria-label="New conversation" title="New conversation" disabled={guide.pending} onClick={guide.restart} className="rounded-lg p-2 hover:bg-secondary"><RotateCcw className="size-4"/></button></div><div role="log" aria-label="Conversation with TinkrBot" aria-live="polite" aria-relevant="additions" className="h-[52dvh] min-h-72 max-h-[650px] overflow-y-auto overscroll-contain p-4 sm:p-6">{guide.messages.map((message, index) => <div key={message.id} className={`mb-5 ${message.role === 'user' ? 'ml-auto max-w-[85%]' : 'max-w-full'}`}><p className="mb-1 text-xs font-semibold text-muted-foreground">{message.role === 'user' ? 'You' : 'TinkrBot'}</p><div className={message.role === 'user' ? 'rounded-2xl bg-primary px-4 py-3 text-primary-foreground' : 'rounded-2xl bg-secondary/50 px-4 py-3'}><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{message.content}</p>{message.role === 'assistant' && <Cards message={message}/>}{message.panel === 'review' && index === guide.messages.length - 1 && <Review />}</div>{message.role === 'assistant' && index === guide.messages.length - 1 && message.suggestions && <div className="mt-3 flex flex-wrap gap-2">{message.suggestions.map(s => <button key={s} disabled={guide.pending} className={chip} onClick={() => void guide.ask(s)}>{s}</button>)}</div>}</div>)}<div ref={end}/></div><form onSubmit={submit} className="border-t border-border p-3"><label htmlFor="bot-input" className="sr-only">Message TinkrBot</label><div className="flex items-end gap-2 rounded-2xl border border-input bg-background p-2 focus-within:border-primary"><textarea id="bot-input" rows={2} maxLength={2000} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
        e.preventDefault();
        if (input.trim() && !guide.pending) {
            void guide.ask(input);
            setInput('');
        }
    } }} placeholder={guide.stage === 'email' ? 'Your email address' : guide.stage === 'name' ? 'Your name' : 'Tell me what is on your mind…'} className="min-w-0 flex-1 resize-none bg-transparent px-2 py-1 text-sm outline-none"/><button aria-label="Send message" disabled={!input.trim() || guide.pending} className="rounded-xl bg-primary p-3 text-primary-foreground disabled:opacity-40"><ArrowUp className="size-5"/></button></div><p className="mt-2 px-2 text-[11px] text-muted-foreground">{guide.mode === 'Guided conversation' ? 'Built in guidance is active. ' : ''}Do not share sensitive data. <a href="/privacy" className="underline">Privacy</a></p></form></div><aside className="rounded-3xl border border-border bg-secondary/20 p-5 lg:self-start"><span className="text-xs font-semibold uppercase tracking-widest text-primary">Your brief</span><h2 className="mt-2 text-xl font-bold">An idea taking shape.</h2>{guide.data.message ? <p className="mt-4 whitespace-pre-wrap break-words text-sm" data-testid="brief-goal">{guide.data.message}</p> : <p className="mt-4 text-sm text-muted-foreground">Share a goal. I will help find the next step.</p>}{guide.data.category && <p className="mt-3 rounded-lg bg-primary/10 px-3 py-2 text-xs">{guide.data.category}</p>}<button disabled={guide.pending || guide.sent} onClick={() => guide.prepare()} className="mt-5 w-full rounded-full border border-primary/40 px-4 py-3 text-sm font-semibold hover:bg-primary/10 disabled:opacity-50">{guide.sent ? 'Inquiry sent' : 'Prepare my inquiry'}</button><p className="mt-3 text-xs text-muted-foreground">Nothing sends until you review and confirm.</p></aside></div></div></section>;
}
